import type { Audience, OutputType, Tone, UploadedReference } from "@/lib/ai/schemas";
import { platformRules } from "@/lib/ai/platformRules";

export const bannedPhrases = [...platformRules.bannedPhrases];

export function referenceContext(references: UploadedReference[]) {
  if (!references.length) {
    return "No uploaded reference materials were provided. This is allowed. Generate from the user command and default MyDesk executive style settings. Use conservative assumptions, do not fabricate source-backed claims, and include assumptions in the output. Avoid exact statistics unless the user supplied them in the command; use directional language and mark where source validation is needed.";
  }
  return references
    .map((reference, index) => {
      const text = reference.extractedText?.trim()
        ? reference.extractedText.trim()
        : `[Saved but not parsed] ${reference.warning || "No extracted text available."}`;
      return `Reference ${index + 1}: ${reference.originalName}\n${text}`;
    })
    .join("\n\n---\n\n");
}

export function templateContext(template?: UploadedReference) {
  if (!template) {
    return "No template was uploaded. This is allowed. Use the selected output type and default MyDesk executive structure, tone, formatting, and output shape.";
  }
  const text = template.extractedText?.trim()
    ? template.extractedText.trim()
    : `[Saved but not parsed] ${template.warning || "No extracted template text available."}`;
  return `Template file: ${template.originalName}
Use this template as format guidance. Learn from its visible structure, section rhythm, heading style, formatting discipline, and professional level where the extracted content supports that. Do not copy unrelated template content as facts.

${text}`;
}

export function planPrompt(input: {
  command: string;
  outputType: OutputType;
  audience: Audience;
  tone: Tone;
  count?: number;
  selectedApproach?: string;
  references: UploadedReference[];
  template?: UploadedReference;
}) {
  return `Create a structured JSON output plan.

Command:
${input.command}

Selected output type: ${input.outputType}
Audience: ${input.audience}
Tone: ${input.tone}
Requested slide/page/section count: ${input.count || "Use judgment"}
Selected approach: ${input.selectedApproach || "Not selected"}

Reference materials:
${referenceContext(input.references)}

Template guidance:
${templateContext(input.template)}

The JSON must include:
output_type, title, audience, objective, key_messages, structure, sections_or_slides, assumptions, risks, missing_information, next_actions.

For sections_or_slides, include number, type, headline, key_message, body_points, recommended_visual, speaker_notes, and source_note where relevant.
Preserve the requested objective, tone, audience, and output type.
If a template is uploaded, reflect its structure and level of polish in the plan without inventing source-backed claims.
If reference materials are uploaded, use them as source/context and infer relevant offering language, scope framing, and strategic patterns. If none are uploaded, generate from the command and default MyDesk executive style settings.
If required details are missing but generation can proceed with reasonable assumptions, proceed and make those assumptions explicit in the assumptions array and final output.
For PowerPoint decks:
- sections_or_slides is the exact slide list and must match the requested slide count when provided.
- Every slide needs an action-oriented headline, not a generic topic label.
- Every slide needs one clear message in key_message.
- Use boardroom structures such as executive takeaway, issue / implication / action, market reality / strategic consequence, barrier / unlock / owner, and recommendation / rationale / next step.
- Limit body_points to four or fewer concise points per slide.
- Do not include Date, Presented by, Presenter, Generated by MyDesk, or other client-facing placeholders.
- If exact data is used, add a source_note with a source or explicit caveat. If no uploaded source supports the statistic, prefer directional language and mark "Source needed" rather than inventing an exact figure.
Do not create placeholder slides. Do not fabricate citations.`;
}

export function draftPrompt(planJson: string) {
  return `Generate the draft output in clean markdown based on this plan.

Plan JSON:
${planJson}

Make it concise, senior, specific, and useful. Avoid generic AI phrasing. Include headings appropriate to the output type.
Clearly include the assumptions from the plan when the command required reasonable assumptions.
For PowerPoint decks, write slide-ready content with sharp headlines, strategic implications, concise support, and clear next actions. Avoid textbook bullets, generic pharma language, and visible internal process language.
If no source material was provided in the plan, do not introduce new exact statistics in the draft. Use directional claims and say where source validation is needed.
If uploaded sources are absent or limited, include this exact line near the end: Source verification required before external use.`;
}

export function critiquePrompt(draftMarkdown: string) {
  return `Review this draft and return JSON with summary, issues, compliance_notes, and source_limitations.

Check for vague claims, generic AI phrases, unsupported assertions, weak headlines, excessive fluff, missing business logic, missing implementation detail, poor executive flow, weak next step, unnecessary jargon, overpromising, and pharma/compliance sensitivity.
For PowerPoint decks, specifically check that every slide has an action-oriented headline, one clear message, limited bullets, evidence caveats for exact data, strategic implications, and no placeholders or "Generated by MyDesk" text.

Draft:
${draftMarkdown}`;
}

export function improvePrompt(input: { draftMarkdown: string; critiqueJson: string }) {
  return `Improve the draft using the critique. Return the final version in markdown only.
Include this exact line near the end when the brief lacks uploaded evidence: Source verification required before external use.
Do not use the terms "placeholder", "section 2", "working draft generated locally", or "configure OpenAI" in the final output.
For PowerPoint decks, make the final content boardroom-ready: action headlines, one message per slide, evidence-aware caveats, strategic implications, and clear next actions.
Never include Date, Presented by, Presenter, or Generated by MyDesk in the output.
Do not add exact statistics that were not supported by uploaded source material or already present in the draft with a caveat.
Do not suggest email delivery or draft email copy.
End with:
Status:
- Changed:
- Left untouched:
- Needs attention:

Draft:
${input.draftMarkdown}

Critique:
${input.critiqueJson}`;
}

export function nextActionPrompt(finalMarkdown: string) {
  return `Create next actions as JSON with recommended_next_action, suggested_follow_up_task, and required_inputs_for_next_version.

Do not suggest email delivery or draft email copy. V1 delivery is preview plus local file downloads only.

Final output:
${finalMarkdown}`;
}

export function revisePrompt(input: { finalMarkdown: string; revisionCommand: string }) {
  return `Revise the current output according to the follow-up command. Return revised markdown only.

Follow-up command:
${input.revisionCommand}

Current output:
${input.finalMarkdown}`;
}
