import { platformRules } from "@/lib/ai/platformRules";
import type { OutputPlan } from "@/lib/ai/schemas";
import type { TaskClassification } from "@/lib/ai/taskClassifier";

export type RuleCheckResult = {
  ok: boolean;
  failures: string[];
};

export function validateGeneratedText(text: string, classification: TaskClassification): RuleCheckResult {
  const failures: string[] = [];
  const trimmed = text.trim();
  if (platformRules.fillerOpenings.some((opening) => trimmed.toLowerCase().startsWith(opening.toLowerCase()))) {
    failures.push("response_starts_with_filler");
  }
  if (/lorem ipsum|placeholder|section 2|working draft generated locally|configure openai/i.test(text)) {
    failures.push("placeholder_content_detected");
  }
  if (classification.significance === "significant" && /this is an assumption/i.test(text) === false && /source verification|required|caveat/i.test(text) === false) {
    failures.push("uncertainty_or_source_caveat_missing");
  }
  if (/Status:/i.test(text) === false) {
    failures.push("status_summary_missing");
  }
  return { ok: failures.length === 0, failures };
}

export function validatePlan(plan: OutputPlan, expectedCount?: number): RuleCheckResult {
  const failures: string[] = [];
  if (expectedCount && plan.sections_or_slides.length !== expectedCount) {
    failures.push("requested_structure_or_count_ignored");
  }
  if (plan.sections_or_slides.some((section) => /section \d+|working draft|placeholder/i.test(section.headline))) {
    failures.push("placeholder_slide_detected");
  }
  return { ok: failures.length === 0, failures };
}

export function validatePowerPointQuality(
  plan: OutputPlan,
  finalMarkdown?: string,
  options: { hasReferences?: boolean; command?: string } = {}
): RuleCheckResult {
  const failures: string[] = [];
  const fullText = [
    plan.title,
    plan.objective,
    ...plan.key_messages,
    ...plan.assumptions,
    ...plan.sections_or_slides.flatMap((section) => [
      section.type,
      section.headline,
      section.key_message,
      section.recommended_visual || "",
      section.speaker_notes || "",
      section.source_note || "",
      ...section.body_points
    ]),
    finalMarkdown || ""
  ].join("\n");

  if (/generated by mydesk/i.test(fullText)) failures.push("mydesk_branding_inside_deck");
  if (/\b(?:placeholder|lorem ipsum|tbd|to be added|insert|presented by|presenter|client name)\b/i.test(fullText)) {
    failures.push("placeholder_text_detected");
  }
  if (/(^|\n)\s*date\s*($|\n|:)/i.test(fullText)) failures.push("date_placeholder_detected");

  const genericHeadlinePattern =
    /^(overview|introduction|background|market overview|hpv in india|key messages|recommendations?|conclusion|next steps?|summary|appendix)$/i;
  const actionLanguage =
    /\b(?:shift|prioritize|unlock|reduce|capture|build|focus|sequence|target|convert|protect|expand|accelerate|close|move|shape|fund|partner|recommend|implication|action|why|how|must|should|can)\b/i;

  for (const section of plan.sections_or_slides) {
    const headline = section.headline.trim();
    const keyMessage = section.key_message.trim();
    const slideText = [headline, keyMessage, ...section.body_points, section.source_note || ""].join(" ");

    if (!headline || genericHeadlinePattern.test(headline)) {
      failures.push(`slide_${section.number}_generic_headline`);
    }
    if (headline.split(/\s+/).length < 5 && !actionLanguage.test(headline)) {
      failures.push(`slide_${section.number}_weak_headline`);
    }
    if (!keyMessage || keyMessage.split(/\s+/).length < 8) {
      failures.push(`slide_${section.number}_missing_clear_message`);
    }
    if (section.body_points.length > 4) {
      failures.push(`slide_${section.number}_too_many_bullets`);
    }
    if (section.body_points.some((point) => point.length > 190)) {
      failures.push(`slide_${section.number}_bullet_too_long`);
    }
    if (hasExactData(slideText) && !hasSourceOrCaveat(section.source_note || "")) {
      failures.push(`slide_${section.number}_exact_data_without_source_or_caveat`);
    }
    if (!options.hasReferences && hasUnsupportedExactData(slideText, options.command || "")) {
      failures.push(`slide_${section.number}_unsupported_exact_data_without_references`);
    }
  }

  if (!options.hasReferences && finalMarkdown && hasUnsupportedExactData(finalMarkdown, options.command || "")) {
    failures.push("final_output_unsupported_exact_data_without_references");
  }

  return { ok: failures.length === 0, failures };
}

export function requiresApproachGate(classification: TaskClassification, selectedApproach?: string) {
  return classification.needs_approach_selection && !selectedApproach;
}

function hasExactData(value: string) {
  return /\b\d+(?:\.\d+)?\s?%|\b\d+(?:\.\d+)?\s?(?:million|billion|crore|lakh|thousand|mn|bn)\b/i.test(value);
}

function hasSourceOrCaveat(value: string) {
  return /\b(?:source|caveat|source needed|verification required|estimate|assumption|directional)\b/i.test(value);
}

function hasUnsupportedExactData(value: string, command: string) {
  const commandData = new Set(extractExactData(command).map((item) => item.toLowerCase()));
  return extractExactData(value).some((item) => !commandData.has(item.toLowerCase()));
}

function extractExactData(value: string) {
  return value.match(/\b\d+(?:\.\d+)?\s?%|\b\d+(?:\.\d+)?\s?(?:million|billion|crore|lakh|thousand|mn|bn)\b/gi) || [];
}
